name: Dual Publish

on:
  workflow_dispatch:
    inputs:
      publish_to_npm:
        description: 'Publish to npm?'
        required: false
        default: 'true'
      publish_to_github:
        description: 'Publish to GitHub Packages?'
        required: false
        default: 'true'

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Run tests
        run: pnpm test

      - name: Run lint
        run: pnpm run lint

      - name: Build project
        run: pnpm run build

      # ---------- NPMJS.ORG PUBLISH ----------
      - name: Prepare .npmrc for npmjs.org
        if: ${{ github.event.inputs.publish_to_npm == 'true' }}
        run: echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > ~/.npmrc
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Publish to npm
        if: ${{ github.event.inputs.publish_to_npm == 'true' }}
        run: npm publish --access public
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      # ---------- GITHUB PACKAGES PUBLISH ----------
      - name: Backup package.json for GitHub Packages
        if: ${{ github.event.inputs.publish_to_github == 'true' }}
        run: cp package.json package.json.backup

      - name: Rewrite package.json for GitHub Packages
        if: ${{ github.event.inputs.publish_to_github == 'true' }}
        run: |
          jq '.name = "@devints47/pixel-forge" | .bin = {
            "pixel-forge": "dist/src/cli/index.js",
            "pforge": "dist/src/cli/index.js"
          }' package.json > package.json.tmp
          mv package.json.tmp package.json

      - name: Prepare .npmrc for GitHub Packages
        if: ${{ github.event.inputs.publish_to_github == 'true' }}
        run: |
          echo "@devints47:registry=https://npm.pkg.github.com" > ~/.npmrc
          echo "//npm.pkg.github.com/:_authToken=${GITHUB_TOKEN}" >> ~/.npmrc
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish to GitHub Packages
        if: ${{ github.event.inputs.publish_to_github == 'true' }}
        run: npm publish --access public --registry=https://npm.pkg.github.com
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Restore package.json
        if: ${{ github.event.inputs.publish_to_github == 'true' }}
        run: mv package.json.backup package.json

